--
Keyset Resources
The following is a section of resources related to the nsset
--

Detail keysetu
GET /keysets/{handle}
< 200
< Content-Type: application/json
{ "handle":"1AB23ORM",
  "dns_keys":[
      {
          "flags":"0",
          "protocol":"3",
          "algorithm":"5",
          "public_key":"AQO1gtiQNJnn/9e5cR76I3Tn1ziRs/p4Ba3wq5jvY1ZOAEfulGBxZy59qj3iLWVyWd5dzYF2KqBES6oToCGxMXmVAP+QIAUCjWR72kwlTyCpg7ZMd2PrcGjAzqPOoFlR7vdYGpIslzbwI71OOZQ7CVLDR8slR16qOMC8Yai8IM9dtmptPRPCEdhM/3T576uPtZGVgGFdCixI9XeN3p8q38FsE7T0wbEUYZBwF1AUrlo2T2d9/6v8wdktxGemxPAX6mXWOYfE3xY0zkoAwcHt5HiB1d/cOr6JB0gJto6gHkfBccIlU/2cJ/Bg3K6A3ER8uPFcCGCuMOA2Qb62IDg0XCA76bJlh1BocPzAjlG8beI9dJz3CZTIW0apneNb4lGyGVmAc2GxvrL/y7GHe9UfwqTnKzXDJcCzKahRNB9xD9TCuUIyChinnxys4BXcGRjMEwPttihgdWjFKDXEWgY7QAMAL1s+hQzWM5TZ2FhSw+tlH4GuH+saeVJ40bdppsqXLD8gwrG9bH6lX6Hu/SIG89WLTC08+mbhg1GDXvti9p/Y4u+EfV69eAG85y9F/tOYvR9Us0llWzg2gtnJr1y/qCgT9bVsyp6xGAd30H0Z0pYr/xXzb4TnKVWZoZGEPdh47dAteFW0R+37Nl62l7dOuunQgzY/RQVli3+fG1Gxizn0tQ=="
      }
  ],
  "technical_contacts":[
      {"handle":"PRVNI"},
      {"handle":"DALSI"}
  ]
}

