HOST: http://mojeid.1x.sk/

--- MojeID 1X public API---
---
# Structure of resources
## Registry objects
Available at URL: https://mojeid.1x.sk/api/v1/

Resouces:

- Domains
- Contacts
- Nssets
- Keysets

---

